/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define EnableDragDrop 1
#define WantOSGLUSDL 1

#define kStrAppName "Mini vMac"
#define kAppVariationStr "minivmac-3.7-retro"
#define kStrCopyrightYear "2020"
#define kMaintainerName "jason@linearsoft.com"
#define kStrHomePage "https://github.com/LinearSoft"
